# Generated by Django 5.1.1 on 2024-11-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_category_customuser_contact_no_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
