# Generated by Django 5.1.1 on 2024-11-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_customuser_age_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(null=True, upload_to='Media/Post_images'),
        ),
    ]
